#!/usr/bin/env node
/* =====================================================================
   visual-audit.js — OPTIONAL responsive screenshot QA (requires Playwright).
   Install once: npm i -D playwright && npx playwright install chromium
   Run: node scripts/visual-audit.js  (dev server must be running on :3000)
   For every public page, waits for fonts + network idle, captures screenshots
   at production QA desktop/tablet/mobile sizes, and flags blank/black pages, horizontal overflow,
   console errors and failed requests. Saves to qa/after-fix/ and writes
   VISUAL-AUDIT.md with PASS/WARNING/FAIL per page.
   ===================================================================== */
import { mkdirSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

let chromium;
try { ({ chromium } = await import("playwright")); }
catch {
  console.log("Playwright is not installed — skipping visual QA.\n" +
    "To enable: npm i -D playwright && npx playwright install chromium");
  process.exit(0);
}

const BASE = process.env.QA_BASE || "http://localhost:3000";
const root = process.cwd();
const pages = readdirSync(root).filter((f) => f.endsWith(".html") && f !== "404.html").map((f) => (f === "index.html" ? "/" : "/" + f));
try { for (const f of readdirSync(join(root, "resources"))) if (f.endsWith(".html")) pages.push("/resources/" + f); } catch {}

const viewports = [
  { name: "1920", width: 1920, height: 1080 },
  { name: "1440", width: 1440, height: 900 },
  { name: "1280", width: 1280, height: 800 },
  { name: "1024", width: 1024, height: 768 },
  { name: "768", width: 768, height: 1024 },
  { name: "430", width: 430, height: 932 },
  { name: "390", width: 390, height: 844 },
  { name: "375", width: 375, height: 812 }
];
const shotDir = "qa/after-fix";
mkdirSync(join(root, shotDir), { recursive: true });

const browser = await chromium.launch();
const rows = [];
for (const path of pages) {
  const slug = path === "/" ? "home" : path.replace(/\//g, "_").replace(/^_|\.html$/g, "");
  let status = "PASS";
  const notes = [];
  for (const vp of viewports) {
    const ctx = await browser.newContext({ viewport: { width: vp.width, height: vp.height } });
    const pg = await ctx.newPage();
    const errs = [];
    pg.on("console", (m) => m.type() === "error" && errs.push(m.text()));
    pg.on("requestfailed", (r) => errs.push("REQ FAIL " + r.url()));
    const resp = await pg.goto(BASE + path, { waitUntil: "networkidle" }).catch(() => null);
    await pg.evaluate(() => document.fonts && document.fonts.ready).catch(() => {});
    await pg.waitForTimeout(400);
    const info = await pg.evaluate(() => {
      const b = document.body;
      const text = (document.querySelector("main")?.innerText || "").trim();
      return {
        scrollW: document.documentElement.scrollWidth,
        innerW: window.innerWidth,
        textLen: text.length,
        bg: getComputedStyle(b).backgroundColor
      };
    });
    if (!resp || resp.status() >= 400) { status = "FAIL"; notes.push(`${vp.name}: HTTP ${resp ? resp.status() : "ERR"}`); }
    if (info.scrollW > info.innerW + 1) { status = "FAIL"; notes.push(`${vp.name}: h-overflow ${info.scrollW}>${info.innerW}`); }
    if (info.textLen < 120) { status = "FAIL"; notes.push(`${vp.name}: blank/empty (${info.textLen} chars)`); }
    if (errs.length) { if (status === "PASS") status = "WARNING"; notes.push(`${vp.name}: ${errs.length} console/req errors`); }
    await pg.screenshot({ path: join(root, shotDir, `${slug}-${vp.name}.png`), fullPage: vp.name === "1440" });
    await ctx.close();
  }
  rows.push({ path, status, notes });
  console.log(`${status.padEnd(7)} ${path}${notes.length ? " — " + notes.join("; ") : ""}`);
}
await browser.close();

const md = `# VISUAL-AUDIT\n\nGenerated by \`scripts/visual-audit.js\` against ${BASE}. Screenshots in \`qa/after-fix/\`.\n\n| Page | Status | Notes |\n| --- | --- | --- |\n` +
  rows.map((r) => `| ${r.path} | ${r.status} | ${r.notes.join("; ") || "—"} |`).join("\n") + "\n";
writeFileSync(join(root, "VISUAL-AUDIT.md"), md);
console.log("\nWrote VISUAL-AUDIT.md");
if (rows.some((r) => r.status === "FAIL")) process.exit(1);
